language: ruby
rvm:
  - 2.1
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
notifications:
  email:
    recipients:
      - "justin@curationexperts.com"
      - "matt@curationexperts.com"
      - "alicia@curationexperts.com"
    on_success: "change"
    on_failure: "always"
  irc:
    channels:
      - "irc.freenode.org#curationexperts"
    template:
      - "%{repository}//%{branch}@%{commit} by %{author}: %{message} - %{build_url}"
